import { Card } from "./Cards"
import WeatherAppImg from '../files/WeatherApp.webp'
import ISROImg from '../files/ISRO.webp'
import TakkenImg from '../files/takken.webp'
import IgnouImg from '../files/ignou.webp'
import UserImg from '../files/user.webp'
import JokeImg from '../files/joke.webp'
import CalculatorImg from '../files/calculator.webp'
import clockImg from '../files/ClockBackground.webp'
import kawasakiImg from '../files/kawasaki.webp'
export function Projects(){
    
    return(
        
        <div className="mb-5">
       
       <h1 className="text-3xl text-center ease-in duration-300 font-bold mb-3 mt-6 ">UI Projects</h1>
       <div className="md:grid md:grid-cols-3 gap-8 px-8">

        <Card id='first' title='Weather App' btn="Open"  to='/weather' img={WeatherAppImg} alt="project preview" content='The ReactWeatherApp is a web application that allows users to search for weather information by entering a city name. Built using React framework, it retrieves weather data for the specified city from the OpenWeatherMap API and displays current weather conditions like temperature, humidity, wind speed, and more, along with a five-day forecast. The application features a clean and modern design, is responsive and intuitive, and includes error handling. With its modular code, CSS preprocessors, and responsive design, the ReactWeatherApp delivers a high-quality user experience across all devices, making it a useful tool for anyone who needs to check the weather in a specific city.'/>
        <Card id='Third' title='Takken' btn="Open" to='https://dark2022.000webhostapp.com/' target='_blank' img={TakkenImg} alt="project preview" content='The Tekken 7 game website clone project using Bootstrap is a web development practice project that I created to replicate the official website of the popular fighting game Tekken 7 using the Bootstrap framework. The project involved utilizing Bootstrap built-in responsive design and grid system to create a visually appealing and user-friendly interface with clear navigation. The website clone features game information, character profiles, and gameplay trailers just like the original website, and I included additional features such as interactive character selection, game mechanics explanations, and community forums. Through this project, I aimed to demonstrate my ability to utilize Bootstrap to create a fully functional replica of an existing website'/>
        <Card id='second' title='ISRO' btn="Open" to='https://vishalking758.github.io/Isro/' target='_blank' img={ISROImg} alt="project preview" content='The ISRO website is a practice project that I designed to enhance my web development skills. The project aims to replicate the design and layout of the official website of the Indian Space Research Organisation (ISRO) using modern web development technologies such as HTML, CSS, and JavaScript. The website features a clean and professional design, with a focus on providing easy navigation and accessibility to users. The project also involves implementing responsive design principles to ensure optimal viewing experience across various devices. Through this project, I aimed to showcase my ability to create well-designed and functional websites while honing my web development skills.'/>
        <Card id='fourth' title='IGNOU' btn="Open" to='https://vishalking758.github.io/ignou/' target='_blank' img={IgnouImg} alt="project preview" content='The IGNOU website clone project using Bootstrap is a web development practice project that I created to replicate the official website of Indira Gandhi National Open University (IGNOU) using the Bootstrap framework. The project involved utilizing Bootstrap built-in responsive design and grid system to create a visually appealing and user-friendly interface with clear navigation. The website clone features information on courses offered, admission procedures, and student services just like the original website. I also included additional features such as a student login portal, student support forums, and course feedback forms. Through this project, I aimed to demonstrate my ability to utilize Bootstrap to create a fully functional replica of an existing website while enhancing my web development skills.'/>
        <Card id='nine' title='Kawasaki' btn="Open Repo" to='https://github.com/Vishalking758/kawasaki' target='_blank' img={kawasakiImg} alt="project preview" content='The "Kawasaki Home Page" project is a web page designed using HTML, CSS, and the Bootstrap framework that showcases Kawasaki,s products and services. The page features a modern and responsive design that includes various sections such as a hero section, product display section, and contact section. The project aims to provide a visually appealing and user-friendly interface for users to explore Kawasaki,s offerings.'/>
       </div>
       <h1 className="text-3xl text-center ease-in duration-300 font-bold mb-3 mt-6 ">Mini Projects</h1>
       <div className="md:grid md:grid-cols-3 gap-8 px-8">

        <Card id='seven' title='Calculator' btn="Open" to='/calculator' img={CalculatorImg} alt="project preview" content='The "Calculator" project is a web application that provides users with a basic calculator interface to perform arithmetic operations. The project is built using React.js, a popular JavaScript library for building user interfaces. The application allows users to perform operations such as addition, subtraction, multiplication, and division. Users can also clear the input and output fields, and use the decimal point to perform decimal calculations.'/>
        <Card id='five' title='Clock' btn="Open" to='/clock' img={clockImg} alt="project preview" content='The "Analog Clock" project is a web application that displays the current time in an analog clock format. The project is built using React.js, a popular JavaScript library for building user interfaces. The application displays the current time in hours, minutes, and seconds, and is designed to resemble a traditional analog clock with hour, minute, and second hands.'/>
        <Card id='eight' title='User' btn="Open" to='/RendomeUser' img={UserImg} alt="project preview" content='The "RendomeUser" project is a React.js web application that uses the "https://randomuser.me/api/" API to generate and display random user profiles. The application fetches user data from the API using HTTP requests, parses it, and stores it in the application state. The user profiles are then rendered on the front-end, where they can be viewed by users in various formats, such as list or grid view. The project can be customized with features such as pagination, search and filter functionality, and sorting based on different criteria. The application can also be made responsive to ensure that it works well on different screen sizes and devices. The project showcases the potential of React.js and external APIs to create engaging and user-friendly web applications with dynamic and constantly updated content. The Random User API is a useful tool for generating realistic-looking user profiles for testing or demo purposes, and it can be integrated into various web applications to provide relevant and up-to-date user data.'/>
        <Card id='six' title='Joke' btn="Open" to='/joke' img={JokeImg} alt="project preview" content='The "Rendome Hindi Joke" project is a web application that fetches and displays random Hindi jokes from the "https://hindi-jokes-api.onrender.com/jokes" API. The project is built using React.js, a popular JavaScript library for building user interfaces. The application fetches the Hindi jokes from the API using HTTP requests and stores them in the application state, which is then passed down as props to various React components. The Hindi jokes are then displayed on the front-end in a user-friendly format. The application can be customized to include features such as pagination, search and filter functionality, and sorting based on different criteria. The use of the Hindi Jokes API in this project is a great example of how external APIs can be used to provide dynamic and constantly updated content to users. The "Rendome Hindi Joke" project is an excellent showcase of how React.js can be used to build interactive and engaging web applications in different languages.'/>
        </div>
       
       
    </div>
 
    )
}